name: Build and package freeswitch

on:
  push:
    branches:
      - main

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: us-west-2

jobs:
  install_and_package:
    runs-on : ubuntu-latest
    steps:
    # - name: Install FreeSWITCH
    #   run: |
    #     ls
    #     chmod +x install-fs.sh
    #     sudo ./install-fs.sh
    
    # - name: Package FreeSWITCH
    #   run: |
    #     chmod +x package-fs.sh
    #     ./package-fs.sh
    
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: freeswitch-package
        path : install*.sh

  
  # upload:
  #   runs-on: ubuntu-latest

  #   needs: build  # This ensures the 'build' job is completed before starting this job

  #   steps:
  #   # Download zip file that was uploaded from the build stage
  #   - name: Download artifact
  #     uses: actions/download-artifact@v4
  #     with:
  #       name: test-bash-file

  #   # Upload the zip file to the s3 bucket
  #   - name: Copy files to the test-prod S3 bucket
  #     run: |
  #       aws s3 cp install-fs.sh s3://balian-repo-public/freeswitch/install-fs.sh