name: Build and package freeswitch

on:
  push:
    branches:
      - main

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: us-west-2

jobs:
  install_and_package:
    runs-on : ubuntu-latest
    steps:
    - name: Install FreeSWITCH
      run: |
        ls
        chmod +x install-fs.sh
        sudo ./install-fs.sh
    
    - name: Package FreeSWITCH
      run: |
        chmod +x package-fs.sh
        ./package-fs.sh
    
    - name: Upload FreeSWITCH .deb package as artifact
      uses: actions/upload-artifact@v4
      with:
        name: freeswitch-deb-package
        path: *.deb

  
  upload_to_s3:
      runs-on: ubuntu-latest

      needs: install_and_package
      steps:
      # Download the .deb package artifact
      - name: Download FreeSWITCH .deb package artifact
        uses: actions/download-artifact@v4
        with:
          name: freeswitch-deb-package

      # Upload the .deb package to S3
      - name: Upload .deb package to S3
        run: |
          DEB_PACKAGE_NAME=$(ls *.deb)
          aws s3 cp $DEB_PACKAGE_NAME s3://balian-repo-public/freeswitch/$DEB_PACKAGE_NAME