name: Build and Package FreeSWITCH

on:
  push:
    branches:
      - main

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: us-west-2

jobs:
  build_and_package:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2
      
      - name: Set up Docker Build Environment
        run: |
          docker run --rm -dit --name fs-build-env -v ${{ github.workspace }}:/workspace debian:bullseye bash
          docker exec fs-build-env bash -c "apt-get update && apt-get install -y build-essential devscripts fakeroot wget"

      - name: Install FreeSWITCH dependencies and build
        run: |
          docker exec fs-build-env bash -c "cd /workspace && chmod +x install-fs.sh && ./install-fs.sh"
      
      - name: Package FreeSWITCH
        run: |
          docker exec fs-build-env bash -c "ls /usr/local/bin"
          docker exec fs-build-env bash -c "ls /var/lib/freeswitch"
          docker exec fs-build-env bash -c "ls /usr/local/share/freeswitch"
          docker exec fs-build-env bash -c "ls /etc/freeswitch"
          docker exec fs-build-env bash -c "cd /workspace && chmod +x package-fs.sh && ./package-fs.sh"
      
      - name: Extract the .deb package from Docker
        run: |
          docker cp fs-build-env:/workspace/freeswitch.deb ./
          docker stop fs-build-env

      - name: Upload FreeSWITCH .deb package as artifact
        uses: actions/upload-artifact@v4
        with:
          name: freeswitch-deb-package
          path: freeswitch.deb

  upload_to_s3:
    runs-on: ubuntu-latest
    needs: build_and_package

    steps:
      - name: Download FreeSWITCH .deb package artifact
        uses: actions/download-artifact@v4
        with:
          name: freeswitch-deb-package

      - name: Upload .deb package to S3
        run: |
          aws s3 cp freeswitch.deb s3://balian-repo-public/freeswitch/freeswitch.deb